import Header from "@/components/header/Header";
import NotificationContainer from '@/components/generalComponents/NotificationContainer';
import ClientLayout from './ClientLayout';
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link 
          href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;500;600;700&family=JetBrains+Mono:wght@300;400;500;600;700&family=Source+Code+Pro:wght@300;400;500;600;700&family=Roboto+Mono:wght@300;400;500;600;700&family=Ubuntu+Mono:wght@400;700&family=Inconsolata:wght@200;300;400;500;600;700;800;900&family=Space+Mono:wght@400;700&display=swap" 
          rel="stylesheet" 
        />
      </head>
      <body>
        <ClientLayout>
          <Header />
          {children}
          <NotificationContainer />
        </ClientLayout>
      </body>
    </html>
  );
}
